FROM	node:alpine as builder

WORKDIR	/app

COPY	package*.json .
RUN		npm install

COPY	. .

RUN  npm run build

#STAGE-2 : Prepare Nginx

FROM nginx 

#FROM 80

COPY --from=builder /app/build /usr/share/nginx/html 